[project]
name = "basic-todo-app-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.18.5",
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.139.2",
    "greenlet>=3.5.3",
    "sqlalchemy>=2.0.51",
]

[dependency-groups]
dev = [
    "poethepoet>=0.48.0",
]


[tool.poe.tasks]
db-generate = "alembic revision --autogenerate"
db-migrate = "alembic upgrade head"
dev = "fastapi dev app/main.py"